@backendToDoList_HostAddress = https://localhost:7095
@jwt_token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhbGVja3NhbmRyZXdjb250YXRvQGdtYWlsLmNvbSIsImp0aSI6IjA1YzFkNjUwLTI3YzUtNGVmOS1hMTMyLWI2MGI5NThiZmEzZiIsImV4cCI6MTc1NDk0OTgxOSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzA5NSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwOTUifQ.nzfqCxfUOuAOMj-BDzVEtw-2RabRif9xpzY-vmOVEwk

### Cria uma nova tarefa para o usuário autenticado
POST {{backendToDoList_HostAddress}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Testar a API pelo Visual Studio",
  "description": "Usar o arquivo .http para enviar a requisição.",
  "deadline": "2025-12-31"
}
###
